### PR TITLE
Change Audour, REAPER, Renoise

### PR DESCRIPTION
**Pull request by tkna91**

### CODE REVIEW

**Comment by tkna91** [comment]
Sorry, the font size was expressed differently.

**Comment by iguanajuice** [comment]
Please use 100%, 110%, 120%, 125%, 133%, or 150% instead of 'larger' and 'x-large'. Try to make the icons as consistent of a size as possible with other icons, using these values.

Rule of thumb; icons should be a little bigger than a capital letter.

**Comment by tkna91** [comment]
I understand.
I wish I could do something to adjust to the current height +/-, but I don't know how to do it.
https://docs.gtk.org/Pango/pango_markup.html

**Comment by tkna91** [comment]
The representation of the space after the icon should probably also be done in the markup

**Comment by iguanajuice** [comment]
> I wish I could do something to adjust to the current height +/-, but I don't know how to do it.

rise='+/-pt'

> The representation of the space after the icon should probably also be done in the markup

It definitely should; but I'm too lazy, and if it ain't broke, don't fix it.

**Pull request merged**
