### PR TITLE
Add qutebrowser, REAPER, Renoise

### PR DESCRIPTION
**Pull request by tkna91**

### CODE REVIEW

**Comment by iguanajuice** [comment]
The icons you have assigned to these apps don't render on my system:
image

Do you have another symbolic icon font installed on your system? Is so, what is it?

**Comment by iguanajuice** [comment]
Closing in favor of this commit: https://github.com/iguanajuice/sway-font-awesome/commit/73390ee09148bd9977dc4a8685e8f5b0b799b462

**Comment by tkna91** [comment]
I was using this one. I think it was probably ttf-roboto-mono-nerd in my environment. Sorry.
https://www.nerdfonts.com/cheat-sheet

- qutebrowser: f01e7
- REAPER: f02c5
- Renoise: e68a

**Comment by iguanajuice** [comment]
Interesting. I might consider nerd-fonts-iconic if font-awesome is not enough.

**Comment by tkna91** [comment]
Yes, I think it is highly expressive, as quite a few icon fonts are merged.

https://www.nerdfonts.com/

image

Some of the mappings overlap with font-awesome and are corrupted, so it would be nice if they could be unified with nerd fonts if possible.

**Comment by iguanajuice** [comment]
I'm thinking of ditching in font-awesome entirely in favor of nerd-fonts-symbols. WAYYYY more options for icons.

**Pull request closed without merging**
